### ISSUE TITLE
Notas sobre o projeto final

### ISSUE THREAD

**Issue by cristian-miew** [senhormiguel/HTML-e-CSS_Final#1]
https://github.com/senhormiguel/HTML-e-CSS_Final/blob/1652bdb0c4afc5fd7aed2d7ccf8c418d8c9a4821/index_desktop.html#L17
- Os últimos dois elementos deviam ficar separados do resto do menu. são elementos separados com ações diferentes do resto do menu. 
```html
<ul class="topnav">
     <li class="logonav"><img src="assets/logo.png" alt="logo"></li>
    <!-- Estes titles não correspondem ao contexto associado. devia ser pricing por exemplo. -->
     <li><a href="" title="fashion" target="_self">Pricing</a></li>
     <li><a href="" title="news" target="_self">About</a></li>
     <li><a href="" title="social" target="_self">Tutorials</a></li>
     <li><a href="" title="sports" target="_self">Blog</a></li>
</ul>

<!-- Estes dois representam outras ações que não o menu. 
     <li class="right">
          <a href="" title="sign in" target="_self"><button class="button buttonS">Sign up</button></a>
     </li>
     <li class="right">
          <a href="" title="sign up" target="_self"><button class="button button0">Sign in</button></a>
     </li>
```
---
https://github.com/senhormiguel/HTML-e-CSS_Final/blob/1652bdb0c4afc5fd7aed2d7ccf8c418d8c9a4821/index_desktop.html#L28
- Elemento estruturalmente irrelevante. Poderia ser feito de outra maneira. Como com um pseudo elemento no elemento seguinte. Um ::before por exemplo.

---
https://prnt.sc/6kGbTfZYPN9L
- O vídeo encontra-se desalinhado do restante conteúdo. 

---
https://github.com/senhormiguel/HTML-e-CSS_Final/blob/1652bdb0c4afc5fd7aed2d7ccf8c418d8c9a4821/index_desktop.html#L52
- Bom uso de classes separadas com significados diferentes. Sugeria que o `button3` fosse mais declarativo `button--blue` por exemplo. é mais fácil de entender o seu significado. 

---
https://github.com/senhormiguel/HTML-e-CSS_Final/blob/1652bdb0c4afc5fd7aed2d7ccf8c418d8c9a4821/index_desktop.html#L66
- Evita os breaklines `<br />` que tens espalhados ao longo do código, não estão a fazer nada em elemento de block. 

---
https://github.com/senhormiguel/HTML-e-CSS_Final/blob/1652bdb0c4afc5fd7aed2d7ccf8c418d8c9a4821/index_desktop.html#L251
- Evita css inline quando já tens folhas de estilo externa. Só te cria confusão na organização do css e cria cenários de precedência. Corres o risco de estar a aplicar css externo que não terá efeito. 

---
Tens demasiada repetição de css que poderia ser só uma classe, por exemplo: 
```css
.button11 {
	padding: 4px 8px 4px 8px;
	gap: 10px;
	border-radius: 19px 19px 19px 19px;
	background: #0064DA;
	color: #FFFFFF;
	/*border: none; */
	border: 0.5px 0px 0px 0px;
	cursor: pointer;
}
```

é o mesmo que: 
```css
.button13 {
	padding: 4px 8px 4px 8px;
	gap: 10px;
	border-radius: 19px 19px 19px 19px;
	background: #0064DA;
	color: #FFFFFF;
	/*border: none; */
	border: 0.5px 0px 0px 0px;
	cursor: pointer;
}
```

estás a repetir código, sem necessidade. Bastava teres uma classe única e aplicares aos locais / elementos que devem ser iguais. é o conceito de reutilização que tens ter que em conta. As classes não são identificadores, são classificadores. 
as cadeiras são todas cadeiras `class="chair"` até que umas são amarelas `class="chair chair--yellow"` e outras vermelhas `class="chair chair--red"`. 
Tens que planear os elementos que são iguais e o que os torna diferentes. Os botões são todos botões, embora uns redondos e outros quadrados e uns amarelos e outros pretos,são os modificadores que os alteram.

---
https://github.com/senhormiguel/HTML-e-CSS_Final/blob/1652bdb0c4afc5fd7aed2d7ccf8c418d8c9a4821/land.css#L523
Classe sem contexto. porque não `.author` ? 
---
https://github.com/senhormiguel/HTML-e-CSS_Final/blob/1652bdb0c4afc5fd7aed2d7ccf8c418d8c9a4821/land.css#L646C1-L664C2
Este código poderia ser tudo dentro da mesma query: 
```css
@media only screen and (max-width: 600px) {
	.button3{
		margin-left: 232px;
	}
}
/* botões */
@media only screen and (max-width: 600px) {
	.buttons{
		margin-left: 30%;
		/*margin-left: 170px;*/

	}
}
/* quatro botões */
@media only screen and (max-width: 600px) {
	.fourbuttons{
		margin-left: 120px;
	}
}
```

ficava assim: 
```css
@media only screen and (max-width: 600px) {
	.button3{
		margin-left: 232px;
	}
 
	.buttons{
		margin-left: 30%;
		/*margin-left: 170px;*/

	}
 
	.fourbuttons{
		margin-left: 120px;
	}
}
```

### Resumo
- Tens uma discrepância muito grande entre o figma e o produto final, tens que ter mais atenção ao detalhe. O que entregas deve ser a imagem do projeto idealizado no figma, é o trabalho que o design espera do desenvolvimento. É importante que tenhas noção que o nosso trabalho é montar o que o design idealizada.
- O teu html está melhor que o css, embora estruturalmente ainda precise de trabalho.
- Tens muita necessiade de duplicação no css, o que é expectável num trabalho de início de carreira mas é algo que tens que corrigir no futuro. Um melhor planeamento no início do projeto poderia ajudar-te a ter um código mais limpo. Começar pela identificação de elementos parecidos, estruturas de dados que se repitam e a sua relação com os restantes elementos da vista. 
- O repositório está mal organizado, tens ficheiros que não são relacionados com o projeto como o "sass.txt" que não está a fazer nada no repositório. 

Em suma, o trabalho não está mal para um primeiro trabalho mas nota-se que requer muito estudo ainda e que tem um défice de organização. Creio que será algo que consigas colmatar no futuro com alguma dedicação.
